import "./globals.css";
import type { Metadata } from "next";
import { Cabin } from "next/font/google";

const inter = Cabin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real Assist Assignment",
  description: "Generated by Real Assist Assignment",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
